language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
install:
   - pip install -r requirements.txt
env:
  - ENV=DEV
#  - ENV=TEST
  - ENV=PROD
script: nosetests --with-coverage -v tests


