language: python
python:
- '2.7'
- '3.5'
- pypy
install:
- pip install -r requirements.txt
env:
- ENV=DEV
- ENV=PROD
script: nosetests --with-coverage -v tests
after_success:
- coveralls
matrix:
  fast_finish: true
deploy:
  provider: heroku
  api_key:
    secure: bR8B4n3cjAafhistBux8qUNFn/1L9TEi2r94OoQZGFuscO6Tli44qCGG/huL5pLWQtVwsiClxqHimcINjStLELFbgpOr2KvKRHBQKemwgPF15b7ekWDFg2RHFIC4Gf9XRT+B3cHhf3wwVVaIcB12vB48tfxPQ50z7nwH63CZMf52y9odDzZPC4gU+A1RZcqaZA3VR9axh7t//oqLjQWHkOzM4gpJNui4044esnRIbR7tFN1qsJbnOS6mc2kAsQiPrWQgyXFxhPsdDeajRMLfX+6jHG/HXsXPRPNPnHvb6OGwiw+sKnf8jjuHgr5OaX7jBKkHPnNA+MrgnxRO+UY0slP+1ymtPjhxKCNf77rfYA3nHg4jrqxmwm6wU0lC+hpf+LHi+fOIvfrrUtB19Db2Lph6FEGALlKP0a++Rq6LAgiv80wo+sKhDMrodwlofaEmSOPPrLJKfq4fRVXE57Yg2p0DkHiZ6lpixJgKY55TEXmvadHe2IgjKbsgGwOktC35A7ioBRHAAWr/ZqLu3yV2SdKtbiuhhjwHQVh1dhRFtszoLspeGhu6XaB94Nw9eFeN4E1S6TCGBMNWbzRyzI4x2EIsx0wd0CY9g0jzurd4gQx1uWmsvFXPnaIJxuIf4gCPEn2pWldTa1aVh5DJJDt6EL/S5P/SZV0+jByPUlINp5U=
  on:
    python: 2.7
