language: python
python:
  - "2.7"
  - "3.5"
#  - "3.2"
#  - "3.3"
#  - "3.4"
  
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
install:
  - sudo easy_install Flask
  - sudo easy_install Coverage
  - pip install coverage
# command to run tests
script: nosetests --with-coverage tests


